### ISSUE TITLE
Issue with reflex.dev documentation

### ISSUE THREAD

**Issue by lupydev** [reflex-dev/reflex-web#1138]
Path: /docs/hosting/deploy-with-github-actions

there's a typo `\` between curly braces `{\{` in auth_token and project_id

```
name: Deploy Reflex App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Reflex Cloud
        uses: reflex-dev/reflex-deploy-action@v1
        with:
          auth_token: ${\{ secrets.REFLEX_PROJECT_ID }}
          project_id: ${\{ secrets.REFLEX_PROJECT_ID }}
          app_directory: "my-app-folder" # Optional, defaults to root
          extra_args: "--env THIRD_PARTY_APIKEY=***" # Optional
          python_version: "3.12" # Optional
```
